/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTelegramInboundRouteImport } from './routes/api/public/telegram/inbound'
import { Route as ApiPublicHooksRunScheduledRouteImport } from './routes/api/public/hooks/run-scheduled'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramInboundRoute =
  ApiPublicTelegramInboundRouteImport.update({
    id: '/api/public/telegram/inbound',
    path: '/api/public/telegram/inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunScheduledRoute =
  ApiPublicHooksRunScheduledRouteImport.update({
    id: '/api/public/hooks/run-scheduled',
    path: '/api/public/hooks/run-scheduled',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/hooks/run-scheduled': typeof ApiPublicHooksRunScheduledRoute
  '/api/public/telegram/inbound': typeof ApiPublicTelegramInboundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/hooks/run-scheduled': typeof ApiPublicHooksRunScheduledRoute
  '/api/public/telegram/inbound': typeof ApiPublicTelegramInboundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/hooks/run-scheduled': typeof ApiPublicHooksRunScheduledRoute
  '/api/public/telegram/inbound': typeof ApiPublicTelegramInboundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/hooks/run-scheduled'
    | '/api/public/telegram/inbound'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/hooks/run-scheduled' | '/api/public/telegram/inbound'
  id:
    | '__root__'
    | '/'
    | '/api/public/hooks/run-scheduled'
    | '/api/public/telegram/inbound'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicHooksRunScheduledRoute: typeof ApiPublicHooksRunScheduledRoute
  ApiPublicTelegramInboundRoute: typeof ApiPublicTelegramInboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/inbound': {
      id: '/api/public/telegram/inbound'
      path: '/api/public/telegram/inbound'
      fullPath: '/api/public/telegram/inbound'
      preLoaderRoute: typeof ApiPublicTelegramInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-scheduled': {
      id: '/api/public/hooks/run-scheduled'
      path: '/api/public/hooks/run-scheduled'
      fullPath: '/api/public/hooks/run-scheduled'
      preLoaderRoute: typeof ApiPublicHooksRunScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicHooksRunScheduledRoute: ApiPublicHooksRunScheduledRoute,
  ApiPublicTelegramInboundRoute: ApiPublicTelegramInboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
